sudo: required
language: node_js
node_js: '14'
git:
  depth: 1
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- 
  - export PATH=$HOME/.yarn/bin:$PATH ;
install: yarn
script: yarn build
jobs:
  fast_finish: true
  include:
  - stage: deploy
    os: linux
    before_deploy:
      - printf "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}\n" >> ~/.npmrc
      - 
    deploy:
      - provider: script
        script: npm version -no-git-tag-version "0.0.1-$(date +%s)" && npm publish --access public
        on:
          branch: master
        skip_cleanup: true
      - provider: script
        script: npm version -no-git-tag-version && npm publish --access public
        on:
          tags: true
        skip_cleanup: true
