name: Yarn build & test
on:
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Use Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://registry.npmjs.org'
        scope: '@eclipse-che'

    - name: Install dependencies
      run: yarn

    - name: Build extension
      run: yarn build

    - name: Run Test
      run: yarn test
