name: Release to NPM
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: '@eclipse-che'

      - name: Install dependencies
        run: yarn

      - name: Build extension
        run: yarn build

      - name: Run Test
        run: yarn test

      - name: Publish to npm
        run: |
          git config --global user.email "che-bot@eclipse.org"
          git config --global user.name "CHE Bot"

          yarn --new-version version "0.0.1-$(date +%s)"
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
