#
# Copyright (c) 2020-2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Release to NPM
on:
  push:
    branches:
      - "main"

jobs:

  build-and-publish:
    runs-on: ubuntu-20.04
    steps:
      -
        name: "Checkout workspace-client source code"
        uses: actions/checkout@v3
      -
        name: "Use Node 16"
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: '@eclipse-che'
      -
        name: "Install dependencies"
        run: yarn
      -
        name: "Build"
        run: yarn build
      -
        name: "Run unit tests"
        run: yarn test --runInBand
      -
        name: "Publish to npm"
        run: |
          git config --global user.email "che-bot@eclipse.org"
          git config --global user.name "CHE Bot"

          yarn --new-version version "0.0.1-$(date +%s)"
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
